# Run the system integration tests

name: Integration
on: [ push, pull_request ]

jobs:
  main:
    name: Integration
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - uses: actions/checkout@v2
      with:
        path: agora
        # For Codecov
        fetch-depth: 2
        submodules: true

    - name: Prepare compiler
      uses: dlang-community/setup-dlang@v1
      with:
          compiler: ldc-latest

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsodium-dev libsqlite3-dev clang

    - name: Checkout faucet
      uses: actions/checkout@v2
      with:
        path: faucet
        repository: bosagora/faucet
        submodules: true

    - name: Update Faucet submodule to point to our clone
      run: |
        cd ${{ github.workspace }}/faucet/
        git -C submodules/agora fetch origin ${{ github.sha }}:agora-ci-integration-test-donotuse
        git -C submodules/agora checkout     agora-ci-integration-test-donotuse
        # For debug output
        git submodule

    - name: Build Faucet
      run: |
        cd ${{ github.workspace }}/faucet/
        docker build -t bpfk/faucet ${{ github.workspace }}/faucet/

    - name: Test
      run: |
        cd ${{ github.workspace }}/agora/
        ./ci/system_integration_test.d

    - name: Prepare fuzzer
      if: github.event_name == 'push'
      run: |
        cd ${{ github.workspace }}/
        docker pull mcr.microsoft.com/restlerfuzzer/restler:v7.4.0

        sudo apt install nodejs npm
        git clone https://github.com/dcarr178/har2openapi
        cd har2openapi
        npm install
        cp ${{ github.workspace }}/agora/tests/system/config.json.har2openapi config.json

    - name: Generate SPEC
      if: github.event_name == 'push'
      run: |
        cd ${{ github.workspace }}/agora/
        # disable HTTPS on all nodes by removing the related files
        rm -rf tests/system/node/*/*.pem

        # replace https urls with http
        for node in tests/system/node/*;
        do
          sed -i 's/https/http/g' $node/config.yaml;
        done

        # enable proxy on node-2
        cp tests/system/node/2/config.yaml tests/system/node/2/config.yaml.bkp
        echo -e "\nproxy:\n  url: http://har-recorder:8080" >>  tests/system/node/2/config.yaml

        # nobuild, integration test already built the image
        ./ci/fuzz.d nobuild record

        # disable proxy
        rm tests/system/node/2/config.yaml
        mv tests/system/node/2/config.yaml.bkp tests/system/node/2/config.yaml

        cd ${{ github.workspace }}/har2openapi
        # generate spec
        node index.js examples ${{ github.workspace }}/agora/tests/system/output.har

        stat output/examples.spec.json

    - uses: actions/upload-artifact@v2
      with:
        name: OpenAPI Specification
        path: ${{ github.workspace }}/har2openapi/output/examples.spec.json

    - name: Change permission on lst files
      run: |
        # Work around druntime setting the permissions to 600..
        # Need to iterate on the directory to avoid 'list arguments too long'
        cd ${{ github.workspace }}/agora/
        for file in $(find tests/system/node/ -name '*.lst'); do
            sudo chmod 644 $file
        done

    - name: 'Upload code coverage'
      uses: codecov/codecov-action@v1
      with:
        flags: integration
